using System.Text;

namespace RoyalCode.Extensions.SourceGenerator.Generators;

/// <summary>
/// Represents a partial type declaration that contains a class generated by
/// <see cref="ClassGenerator"/>.
/// </summary>
public sealed class ContainingTypeGenerator : GeneratorNode, IWithNamespaces
{
    private GeneratorNodeList? attributes;
    private ModifiersGenerator? modifiers;
    private GenericsGenerator? generics;

    public ContainingTypeGenerator(string name, string typeType = "class")
    {
        Name = name;
        TypeType = typeType;
    }

    public string Name { get; set; }

    public string TypeType { get; }

    public GeneratorNodeList Attributes => attributes ??= new();

    public ModifiersGenerator Modifiers => modifiers ??= new();

    public GenericsGenerator Generics => generics ??= new();

    public IEnumerable<string> GetNamespaces() =>
        generics?.GetNamespaces() ?? Enumerable.Empty<string>();

    public override void Write(StringBuilder sb, int indent = 0)
    {
        WriteOpening(sb, indent);
        sb.Indent(indent).AppendLine("}");
    }

    internal void WriteOpening(StringBuilder sb, int indent)
    {
        attributes?.Write(sb, indent);
        sb.Indent(indent);
        modifiers?.Write(sb);
        sb.Append(TypeType).Append(" ").Append(Name);
        generics?.Write(sb);
        sb.AppendLine();
        sb.Indent(indent).AppendLine("{");
    }
}
