name: generators-nuget

on:
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Build and pack
        run: dotnet build ./RoyalCode.Utils/RoyalCode.Extensions.SourceGenerator/RoyalCode.Extensions.SourceGenerator.csproj -c Release -o ./publish/RoyalCode.Extensions.SourceGenerator
    
      - name: publish nuget package
        run: dotnet nuget push ./publish/RoyalCode.SmartSelector.Generators/**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
