name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./**/*.sln
    - name: Build
      run: dotnet build ./**/*.sln --no-restore -c Release
    - name: Test
      run: dotnet test ./**/*Tests.csproj --no-build --verbosity normal
    - name: Publish
      run: dotnet push ./**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
