name: .NET

on:
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build and pack
      run: sudo /home/runner/.dotnet/dotnet build ./RoyalCode.Utils/RoyalCode.Extensions.PropertySelection/RoyalCode.Extensions.PropertySelection.csproj -c Release --no-restore
    
    - name: publish nuget package
      run: sudo /home/runner/.dotnet/dotnet nuget push ./RoyalCode.Utils/RoyalCode.Extensions.PropertySelection/**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
